language: d
d:
  - dmd

script:
 - dub build -c=eng_exec

notifications:
  webhooks:
    urls: 
    - https://webhooks.gitter.im/e/2230d08f250459935637
    on_success: change
    on_failure: always
    on_start: never